server:
  port: 8081
spring:
  application:
    name: customer-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customer
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka